# Generated by Django 5.0 on 2024-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=1,
                verbose_name="продолжительность выполнения привычки в секундах",
            ),
        ),
    ]
